Repository ransbachm/th-eshop, pull requests merged in 2023-02, with the labels that each got.

#1 Improve search page & fix css error
  src/main/java/moe/pgnhd/theshop/handlers/SearchHandler.java
  src/main/resources/public/static/css/index.css
  src/main/resources/templates/partials/header.hbs
  src/main/resources/templates/search.hbs
Labels: bug, enhancement

#2 Add product creation
  .gitignore
  pom.xml
  public/about_favicon.txt
  public/favicon.ico
  public/static/css/common.css
  public/static/css/partials/footer.css
  public/static/css/partials/header.css
  public/static/css/product/show.css
  public/static/test.html
  src/main/java/moe/pgnhd/theshop/Main.java
  src/main/java/moe/pgnhd/theshop/Management.java
  src/main/java/moe/pgnhd/theshop/Util.java
  src/main/java/moe/pgnhd/theshop/handlers/ProductHandler.java
  src/main/resources/templates/product/create.hbs
  src/main/resources/templates/product/show.hbs
Labels: enhancement

#7 Add ability for user to become seller
  src/main/java/moe/pgnhd/theshop/Main.java
  src/main/java/moe/pgnhd/theshop/Management.java
  src/main/java/moe/pgnhd/theshop/handlers/ProductHandler.java
  src/main/java/moe/pgnhd/theshop/handlers/ProfileHandler.java
  src/main/resources/templates/partials/header.hbs
  src/main/resources/templates/profile.hbs
Labels: bug, enhancement

#17 Fix order page
  src/main/java/moe/pgnhd/theshop/handlers/OrderHandler.java
Labels: bug

#20 Redirect user to login after confirm
  src/main/java/moe/pgnhd/theshop/handlers/RegisterAndLoginHandler.java
Labels: bug

#21 Fix empty arguments if null
  src/main/java/moe/pgnhd/theshop/handlers/SearchHandler.java
Labels: bug

#27 Add logout feature
  public/static/css/partials/header.css
  src/main/java/moe/pgnhd/theshop/Main.java
  src/main/java/moe/pgnhd/theshop/Management.java
  src/main/java/moe/pgnhd/theshop/handlers/Filters/RequireLogin.java
  src/main/java/moe/pgnhd/theshop/handlers/RegisterAndLoginHandler.java
  src/main/java/moe/pgnhd/theshop/model/User.java
  src/main/resources/templates/partials/header.hbs
Labels: bug, enhancement
