Repository ransbachm/th-eshop, pull requests merged in 2023-03, with the labels that each got.

#31 Fix login bug
  src/main/java/moe/pgnhd/theshop/handlers/Filters/RequireLogin.java
Labels: bug

#34 Add Email-Reciept
  src/main/java/moe/pgnhd/theshop/Mail.java
  src/main/java/moe/pgnhd/theshop/Management.java
  src/main/java/moe/pgnhd/theshop/handlers/BasketHandler.java
  src/main/java/moe/pgnhd/theshop/model/Models.java
  src/main/resources/templates/email/receipt.hbs
  src/main/resources/templates/login.hbs
Labels: enhancement

#38 Add Paypal integration
  .env.example
  pom.xml
  public/static/css/button.css
  src/main/java/moe/pgnhd/theshop/EmailSendException.java
  src/main/java/moe/pgnhd/theshop/Main.java
  src/main/java/moe/pgnhd/theshop/Management.java
  src/main/java/moe/pgnhd/theshop/PaymentException.java
  src/main/java/moe/pgnhd/theshop/Payments.java
  src/main/java/moe/pgnhd/theshop/handlers/BasketHandler.java
  src/main/resources/templates/my/basket.hbs
Labels: enhancement

#40 Fix wrongly hardcoded value
  py/calc.py
Labels: bug

#54 Minor fixes
  public/static/secondary/css/index.css
  src/main/resources/templates/secondary/index.hbs
Labels: enhancement, primary-css

#55 Bug fixes
  public/static/secondary/css/login.css
  public/static/secondary/css/my/orders.css
  public/static/secondary/css/register.css
  src/main/java/moe/pgnhd/theshop/Management.java
  src/main/java/moe/pgnhd/theshop/handlers/ProductHandler.java
  src/main/resources/templates/secondary/index.hbs
  src/main/resources/templates/secondary/my/orders.hbs
Labels: enhancement, primary-css, javacode

#56 Update header
  public/static/primary/css/partials/header.css
Labels: bug, primary-css
